spring:
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    application:
        name: fleet-management
springdoc:
    api-docs:
        path: "api-docs"
