CREATE TABLE taxis(
  id INT PRIMARY KEY,
  plate VARCHAR(9) NOT NULL
);

CREATE TABLE trajectories (
  id INT GENERATED ALWAYS AS IDENTITY,
  taxi_id INT NOT NULL,
  date TIMESTAMP NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  CONSTRAINT fk_taxi FOREIGN KEY(taxi_id) REFERENCES taxis(id)
);
